API_URL = 'https://thanados.openatlas.eu/api/'

CSV_TEMPLATE = {
    'id': '',
    'name': '',
    'alias': '',
    'description': '',
    'begin_from': '',
    'begin_to': '',
    'begin_comment': '',
    'end_from': '',
    'end_to': '',
    'end_comment': '',
    'wkt': '',
    'type_ids': '',
    'value_types': '',
    'reference_system_wikidata': '',
    'reference_system_geonames': '',
    'administrative_unit': '',
    'historical_place': '',
    'openatlas_class': '',
    'parent_id': '',
    'openatlas_parent_id': ''}

SITE_TYPE_TABLES = [
    'lastnosti_najdisc_grobisceoddaljenost',
    'lastnosti_najdisc_grobiscepokop',
    'lastnosti_najdisc_grobisceprostor',
    'lastnosti_najdisc_grobiscetip',
    'lastnosti_najdisc_grobisceusmerjenost',
    'lastnosti_najdisc_grobiscevelikost',
    'lastnosti_najdisc_kultniprostortip',
    'lastnosti_najdisc_najdba',
    'lastnosti_najdisc_naselbinatip',
    'lastnosti_najdisc_naselbinautrjenost',
    'lastnosti_najdisc_naselbinavelikost',
    'lastnosti_najdisc_naselbinavrstesledov',
    'lastnosti_najdisc_primarnakategorija',
    'lastnosti_najdisc_topografskalega',
    'lastnosti_najdisc_zakladnanajdbaobmocje']

GRAVE_TYPE_TABLES = [
    'lastnosti_grobov_gradba',
    'lastnosti_grobov_vrsta',
    'lastnosti_grobov_zasutje',
    'lastnosti_grobov_zunanjiznaki']

ARTIFACT_TYPE_TABLES = [
    "lastnosti_predmetov_jagodabarva",
    "lastnosti_predmetov_jagodaokras",
    "lastnosti_predmetov_jagodaprerez",
    "lastnosti_predmetov_jagodasteklo",
    "lastnosti_predmetov_jagodatloris",
    "lastnosti_predmetov_naglavniobrocekoblika",
    "lastnosti_predmetov_ohranjenost",
    "lastnosti_predmetov_nozdrzaj",
    "lastnosti_predmetov_nozhrbetoblika",
    "lastnosti_predmetov_nozhrbetprehod",
    "lastnosti_predmetov_nozkanalzakri",
    "lastnosti_predmetov_nozkonica",
    "lastnosti_predmetov_noznoznica",
    "lastnosti_predmetov_nozoblikatrna",
    "lastnosti_predmetov_nozostrinaoblika",
    "lastnosti_predmetov_nozostrinaprehod",
    "lastnosti_predmetov_nozrezilo",
    "lastnosti_predmetov_posodabarvapreloma",
    "lastnosti_predmetov_okolje",
    "lastnosti_predmetov_snov",
    "lastnosti_predmetov_posodabarvaznotraj",
    "lastnosti_predmetov_posodabarvazunaj",
    "lastnosti_predmetov_posodaizdelava",
    "lastnosti_predmetov_posodaodtis",
    "lastnosti_predmetov_posodaohranjenidel",
    "lastnosti_predmetov_posodaokras",
    "lastnosti_predmetov_posodaprismojeniostanki",
    "lastnosti_predmetov_posodatipustja",
    "lastnosti_predmetov_posodavelikostpustila",
    "lastnosti_predmetov_posodavrstapustila",
    "lastnosti_predmetov_posodavsebnostpustila",
    "lastnosti_predmetov_posodavrstaposode",
    "lastnosti_predmetov_lega",
    "lastnosti_predmetov_vrsta",
    "lastnosti_predmetov_prstanoblika",
    "lastnosti_predmetov_zaponkaoblika"]
