class Place:
    def __init__(self, data):
        self.id_ = data['id']
        self.begin = data['begin']
        self.end = data['end']
        self.name = data['name']
        self.admin_settlement = data['admin_settlement']
        self.admin_unit = data['admin_unit']
        self.admin_district = data['admin_district']
        self.admin_state = data['admin_state']
        self.admin_state2 = data['admin_state2']
        self.first_publication = data['first_publication']
        self.location_precision = data['location_precision']
        self.coordinate = data['coordinate']
        self.location_description = data['location_description']
        self.plot_number = data['plot_number']
        self.data_quality = data['data_quality']
        self.archaeological_quality = data['archaeological_quality']
        self.special_finds = data['special_finds']
        self.comments = data['comments']
        self.primary_chronology = data['primary_chronology']
        self.certainty_of_chronology = data['certainty_of_chronology']
        self.chronology_description = data['chronology_description']
        self.description = data['description']
        self.description_2 = data['description_2']
        self.summary = data['summary']
        self.primary_type_id = data['primary_type_id']
        self.citations = []

    def __repr__(self):
        return str(self.__dict__)
